version: '3'
services:
  bff:
    build: 
      context: ./bff
    ports:
     - "8081:8080"
    env_file:
     - ./environment.env

  authservice:
    build: 
      context: ./authservice
    ports:
     - "8082:8080"
    env_file:
     - ./environment.env


  passservice:
    build: 
      context: ./passservice
    ports:
     - "8083:8080"
    env_file:
     - ./environment.env
    volumes:
     - ./passservice/payara/config:/opt/payara5/glassfish/domains/domain1/config

  generator:
    build: .
    ports:
     - "8085:8080"
    env_file:
     - ./environment.env

     
  # passservice2:
  #   build: 
  #     context: ./passservice
  #   ports:
  #    - "8084:8080"
  #   env_file:
  #    - ./environment.env
  #   volumes:
  #    - ./passservice/payara/config:/opt/payara5/glassfish/domains/domain1/config
